### ISSUE TITLE
The requested path contains null segment at index 0 error after login

### ISSUE THREAD

**Issue by vbishurov** [hansenms/dotnet-angular-oidc#1]
The ConfigService sets the post_login_route but the configuration in the AppModule looks for startup_route.

ConfigService:103 
config.post_login_route = "/home";

app.module.ts:89
openIDImplicitFlowConfiguration.post_login_route = this.oidcConfigService.clientConfiguration.startup_route;

This causes a "The requested path contains null segment at index 0" error to be logged to the console after the user has logged in.

**Comment by hansenms** [comment]
Thanks @vbishurov, I clearly didn't spend a whole lot of time checking all the various corners of this. Was more focused on demonstrating the config backend. If you want to put up a PR with a fix, that would be greatly appreciated.
